import type { LucideIcon } from 'lucide-react';
import {
  HeartHandshake,
  Droplets,
  MapPin,
  User,
  Phone,
  Clock,
  CheckCircle,
  XCircle,
  Plus,
  ChevronRight,
  ShieldCheck,
  Award,
  Calendar,
  LogIn,
  LogOut,
  Bell,
  MessageSquare,
  UserCheck,
  Upload,
  Map,
  History,
  Settings,
  HelpCircle,
  LifeBuoy,
  Trophy,
  MoreVertical,
  LayoutDashboard,
  Send,
  Languages,
  Users,
  SlidersHorizontal,
  Sun,
  Moon,
  UserCog,
  Info,
  Cloud,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: HeartHandshake,
  blood: Droplets,
  location: MapPin,
  user: User,
  users: Users,
  userCheck: UserCheck,
  userCog: UserCog,
  phone: Phone,
  clock: Clock,
  check: CheckCircle,
  close: XCircle,
  add: Plus,
  chevronRight: ChevronRight,
  verified: ShieldCheck,
  award: Award,
  calendar: Calendar,
  login: LogIn,
  logout: LogOut,
  notification: Bell,
  chat: MessageSquare,
  upload: Upload,
  map: Map,
  history: History,
  settings: Settings,
  help: HelpCircle,
  support: LifeBuoy,
  leaderboard: Trophy,
  menu: MoreVertical,
  layoutDashboard: LayoutDashboard,
  send: Send,
  languages: Languages,
  filter: SlidersHorizontal,
  sun: Sun,
  moon: Moon,
  info: Info,
  cloud: Cloud,
};
